# Generated by Django 2.2.4 on 2019-11-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20191112_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='price',
            field=models.IntegerField(),
        ),
    ]
