# Generated by Django 2.2.7 on 2019-11-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20191112_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='price',
            field=models.CharField(max_length=6),
        ),
    ]
