# Generated by Django 2.2.7 on 2019-11-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20191126_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='size',
            field=models.PositiveIntegerField(),
        ),
    ]
